project:
  type: website
  output-dir: docs
resources:
  - Miles_LibbeyV_Resume_2025.pdf

website:
  title: "Miles Libbey V"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: cv.qmd
        text: Resume
        
    right:
      - icon: envelope
        href: mailto:mlibbeyv@gmail.com
      - icon: linkedin
        href: "https://linkedin.com/in/miles-libbey-v"
        target: _blank
      - icon: github
        href: "https://github.com/milesLV"
        target: _blank

format:
  html:
    theme: lumen
    css: styles.css
    toc: true
    link-external-newwindow: true
    page-layout: article
    grid:
      body-width: 1000px     # make the main content wider
      margin-width: 300px    # push the margin (where TOC sits) further right
      sidebar-width: 550px     # optional: hide left sidebar if you have one
      gutter-width: 1.5em
    page-footer:
      left: |
        &copy; Miles Libbey V, 2025<br>
        All content licensed under <i class='bi-badge-cc'></i>
        [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)
      right: |
        Site built with <a href='https://quarto.org/'>Quarto</a>

editor: source

