project:
  type: website
  output-dir: docs
resources:
  - Miles_LibbeyV_Resume_2025.pdf

website:
  title: "Miles Libbey V"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: cv.qmd
        text: Cirriculum Vitae
        
    right:
      - icon: envelope
        href: mailto:mlibbeyv@gmail.com
      - icon: linkedin
        href: "https://linkedin.com/in/miles-libbey-v"
      - icon: github
        href: "https://github.com/milesLV"

format:
  html:
    theme: lumen
    css: styles.css
    toc: true
    page-layout: article
    page-footer:
      left: |
        &copy; [name], 2025<br>
        All content licensed under <i class='bi-badge-cc'></i>
        [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)
      right: |
        Site built with <a href='https://quarto.org/'>Quarto</a>

editor: source

