---
title: "Miles Libbey V"
project:
  type: website
  output-dir: docs

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
---

# About Me

::: {#intro-heading}
Hello! I am Miles Libbey V, I graduated Cum Laude from Macalester College studying Data Science with pursuits in Psychology, Spanish, Linguistics, and Political Science. Not too long ago, I conducted research in Linguistics under the department chair and a team of many students all from varying disciplines in order to produce a pending article about the dissimilarity of vocalic phonation distinctions across sex and gender. I am also involved with many non-profits in the Bay Area (where I am from) and the Twin Cities, the latest being The ARC Minnesota, a nonprofit dedicated to providing support to people wit intellectual development disabilities (IDD) in an array of ways, where I acted as a Development Intern. Outside of work, I really enjoy dancing– at one point I was involved with 3 individual dance groups both in school and outside (though, I am definitely still a learner in this field).
:::

## Education

::: {##intro-heading}
Macalester College 2021 - 2025 \| St. Paul MN

B.A. in Data Science \| Sept 2021 - May 2025
:::
